package ke.co.basecode.dataloading.sync

enum class SyncStatus(val value: String) {

    LOADING_INITIAL("LOADING_INITIAL"), // GETTING INITIAL DATA
    LOADING_INITIAL_FAILED("LOADING_INITIAL_FAILED"), // UNABLE TO GET INITIAL DATA
    LOADING_INITIAL_EXHAUSTED("LOADING_INITIAL_EXHAUSTED"), // NO INITIAL DATA

    LOADING_BEFORE("LOADING_BEFORE"), // GETTING OLDER DATA
    LOADING_BEFORE_FAILED("LOADING_BEFORE_FAILED"), // UNABLE TO GET OLDER DATA
    LOADING_BEFORE_EXHAUSTED("LOADING_BEFORE_EXHAUSTED"), // NO OLDER DATA

    LOADING_AFTER("LOADING_AFTER"), // GETTING NEWER DATA
    LOADING_AFTER_FAILED("LOADING_AFTER_FAILED"), // UNABLE TO GET NEWER DATA
    LOADING_AFTER_EXHAUSTED("LOADING_AFTER_EXHAUSTED"), // UNABLE TO GET NEWER DATA

    LOADED("LOADED"),

    REFRESHING("REFRESHING"),
    REFRESHING_FAILED("REFRESHING_FAILED"),
}